from pydantic import BaseModel, Field

class ResearchRequest(BaseModel):
    topic: str = Field(..., description="Target research topic")
    depth: str = Field(default="medium", description="Research depth: shallow, medium, deep")

class ResearchResponse(BaseModel):
    message: str
    topic: str
    status: str = Field(default="completed")
    result: str = Field(..., description="Final research response generated by the model")