from typing import List, Optional
from pydantic import BaseModel, Field


class ResearchKeyFinding(BaseModel):
    title: str = Field(description="Title of the specific finding or trend")
    description: str = Field(description="Detailed explanation of the finding")


class ResearchReportSchema(BaseModel):
    title: str = Field(description="Main title of the research report")
    executive_summary: str = Field(
        description="A high-level summary of the research topic"
    )
    key_findings: List[ResearchKeyFinding] = Field(
        description="List of key findings or trends identified"
    )
    summary_outlook: Optional[str] = Field(
        default="Ongoing monitoring and further evaluation recommended as the domain continues to evolve rapidly.",
        description="Future outlook or final conclusions"
    )


class ResearchRequest(BaseModel):
    topic: str = Field(..., description="Target research topic")
    depth: str = Field(
        default="medium", description="Research depth: shallow, medium, deep"
    )


class ResearchResponse(BaseModel):
    message: str
    topic: str
    status: str = Field(default="completed")
    result: ResearchReportSchema = Field(
        ..., description="Structured research report generated by the model"
    )